# Generated by Django 2.2.16 on 2022-05-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220517_2031'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='uniqueConstraint_review'),
        ),
    ]
